import { addTypeTemplate, type Resolver } from '@nuxt/kit';

export const registerTypeTemplates = (resolver: Resolver) => {
    addTypeTemplate({
        filename: 'types/sanctum.d.ts',
        getContents: () => `// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from '${resolver.resolve('./runtime/types/config.ts')}';
import type { SanctumGlobalMiddlewarePageMeta } from '${resolver.resolve('./runtime/types/meta.ts')}';

declare module 'nuxt/schema' {
    interface AppConfig {
        sanctum?: SanctumAppConfig;
    }
    interface AppConfigInput {
        sanctum?: SanctumAppConfig;
    }
}

declare module '@nuxt/schema' {
    interface AppConfig {
        sanctum?: SanctumAppConfig;
    }
    interface AppConfigInput {
        sanctum?: SanctumAppConfig;
    }
}

declare module '#app' {
    interface PageMeta {
        /**
         * Sanctum global middleware page configuration.
         */
        sanctum?: Partial<SanctumGlobalMiddlewarePageMeta>;
    }
}

export {};`,
    });
};
